# Generated by Django 3.1.1 on 2020-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
