# Generated by Django 3.1.1 on 2020-10-12 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20200930_2038'),
        ('review', '0002_auto_20200930_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReview',
            new_name='CustomerReview',
        ),
    ]
