# Generated by Django 3.1.1 on 2020-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20201012_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='author',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='comment',
            field=models.TextField(max_length=400),
        ),
    ]
