# Generated by Django 3.1.1 on 2020-09-15 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200915_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserDetails',
        ),
    ]
