# Generated by Django 3.1.1 on 2020-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=20, unique=True),
        ),
    ]
