# Generated by Django 3.1.1 on 2020-09-24 15:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200924_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='product_images/default.jpeg', force_format=None, keep_meta=True, null=True, quality=100, size=[640, 480], upload_to='product_images/'),
        ),
    ]
