# Generated by Django 3.1.1 on 2020-09-30 17:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200924_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='product_images/default.jpeg', force_format=None, keep_meta=True, null=True, quality=90, size=[640, 480], upload_to='product_images/'),
        ),
    ]
