# Generated by Django 3.1.1 on 2020-11-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200930_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='special_price',
        ),
    ]
